### ISSUE TITLE
Спам в консоль

### ISSUE THREAD

**Issue by Notab123** [gepron1x/minimessage-anywhere#1]
[18:44:55 ERROR]: [MiniMessageAnywhere] Unhandled exception number 256 occured in onPacketSending(PacketEvent) for MiniMessageAnywhere
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.reflect.accessors.MethodAccessor.invoke(Object, Object[])" because "com.comphenix.protocol.wrappers.WrappedDataWatcher.SETTER" is null
at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:510) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:525) ~[ProtocolLib (6).jar:?]
at me.gepron1x.minimessageanywhere.packetlistener.out.EntityMetadataListener.onPacketSending(EntityMetadataListener.java:37) ~[MiniMessageAnywhere-2.0.1.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib (6).jar:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib (6).jar:?]
at net.minecraft.network.Connection.writePacket(Connection.java:401) ~[?:?]
at net.minecraft.network.Connection.send(Connection.java:348) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2085) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2071) ~[?:?]
at net.minecraft.server.level.ServerEntity.sendPairingData(ServerEntity.java:284) ~[?:?]
at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:267) ~[?:?]
at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2333) ~[?:?]
at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:1992) ~[purpur-1.18.1.jar:git-Purpur-1434]
at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:393) ~[purpur-1.18.1.jar:git-Purpur-1434]
at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[purpur-1.18.1.jar:git-Purpur-1434]
at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:322) ~[?:?]
at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1661) ~[purpur-1.18.1.jar:git-Purpur-1434]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:516) ~[purpur-1.18.1.jar:git-Purpur-1434]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1494) ~[purpur-1.18.1.jar:git-Purpur-1434]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.1.jar:git-Purpur-1434]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1434]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
При заходе игрока пишется в консоль версия 1.18.1

**Comment by gepron1x** [comment]
Привет, попробуй обновить ProtocolLib. Как временное решение, если не сработает - отключи entities в конфиге.

**Comment by gepron1x** [comment]
Исправлено. Обновись до 2.1.0
