### ISSUE TITLE
Plugin is not enabled on paper 1.20.1

### ISSUE THREAD

**Issue by Fantomrat** [gepron1x/minimessage-anywhere#13]
Plugin disabaling after it create a config

**To Reproduce**
- put the plugin to the server folder
- run the server
- reload the plugin or restart the server

**Expected behavior**
plugin works without errors

**Version Info**
Plugin: MiniMessageAnywhere-2.2.2
Server: paper-1.20.1-156.jar
Protocollib: ProtocolLib v5.1.0
Logs: 
```
[01:11:59] [Server thread/INFO]: [MiniMessageAnywhere] Enabling MiniMessageAnywhere v2.2.2
[01:12:00] [Server thread/ERROR]: Error occurred while enabling MiniMessageAnywhere v2.2.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
	at me.gepron1x.libraries.dazzleconf.ext.snakeyaml.SnakeYamlOptions$Builder.lambda$new$0(SnakeYamlOptions.java:111) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.libraries.dazzleconf.ext.snakeyaml.SnakeYamlConfigurationFactory.loadMapFromReader(SnakeYamlConfigurationFactory.java:131) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.libraries.dazzleconf.factory.AbstractConfigurationFactory$ConfigFactoryDelegate.loadMap(AbstractConfigurationFactory.java:148) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.libraries.dazzleconf.factory.HumanReadableConfigurationFactory.bufferedLoadMap(HumanReadableConfigurationFactory.java:90) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.libraries.dazzleconf.factory.HumanReadableConfigurationFactory.loadMap(HumanReadableConfigurationFactory.java:78) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.libraries.dazzleconf.factory.ConfigurationFormatFactory.load(ConfigurationFormatFactory.java:126) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.libraries.dazzleconf.factory.DelegatingConfigurationFactory.load(DelegatingConfigurationFactory.java:57) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.libraries.dazzleconf.factory.AbstractConfigurationFactory.load(AbstractConfigurationFactory.java:42) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.libraries.dazzleconf.helper.ConfigurationHelper.reloadConfigData(ConfigurationHelper.java:96) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.minimessageanywhere.config.ConfigManager.reloadConfig(ConfigManager.java:40) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.minimessageanywhere.MiniMessageAnywhere.enable(MiniMessageAnywhere.java:85) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.minimessageanywhere.MiniMessageAnywhere.onEnable(MiniMessageAnywhere.java:71) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-156]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-156]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-156]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-156]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-156]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-156]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-156]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-156]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-156]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:12:00] [Server thread/INFO]: [MiniMessageAnywhere] Disabling MiniMessageAnywhere v2.2.2
[01:12:00] [Server thread/INFO]: [MiniMessageAnywhere] Plugin disabled, cya!
```

**Comment by gepron1x** [comment]
A dev build with 1.20.1 is available in our discord.
[discord](https://development.decalium.ru)

**Comment by gepron1x** [comment]
Oops
