### ISSUE TITLE
[MiniMessageAnywhere] Unhandled exception number 4096 occured in onPacketSending(PacketEvent) for MiniMessageAnywhere

### ISSUE THREAD

**Issue by tyushalove** [gepron1x/minimessage-anywhere#3]
Спамит в консоль сообщениями 
MiniMessageAnywhere] Unhandled exception number 4096 occured in onPacketSending(PacketEvent) for MiniMessageAnywhere

и

[10:51:31 ERROR]: [MiniMessageAnywhere] Unhandled exception number 512 occured in onPacketSending(PacketEvent) for MiniMessageAnywhere
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.reflect.accessors.MethodAccessor.invoke(Object, Object[])" because "com.comphenix.protocol.wrappers.WrappedDataWatcher.SETTER" is null
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:510) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:525) ~[ProtocolLib.jar:?]
        at me.gepron1x.minimessageanywhere.packetlistener.out.EntityMetadataListener.onPacketSending(EntityMetadataListener.java:40) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2022) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2008) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendPairingData(ServerEntity.java:285) ~[?:?]
        at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:268) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2308) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2221) ~[?:?]
        at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:1956) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.level.ServerChunkCache.addEntity(ServerChunkCache.java:1174) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2442) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2387) ~[?:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.startTracking(PersistentEntitySectionManager.java:227) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntity(PersistentEntitySectionManager.java:187) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntity(PersistentEntitySectionManager.java:166) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1417) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1324) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:296) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:213) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:183) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1032) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:918) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:625) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1617) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[paper-1.18.1.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-215]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by gepron1x** [comment]
Здравствуй, обнови ProtocolLib

**Comment by tyushalove** [comment]
Я скачивал со spigot.ru

Там последняя версия же, или я что-то не знаю?
