### ISSUE TITLE
Не работает на версий 1.18.2

### ISSUE THREAD

**Issue by Notab123** [gepron1x/minimessage-anywhere#4]
Ядро: Purpur
Версия 1.18.2
При запуске сервера выдаёт эту ошибку

[06:48:46 ERROR]: Error occurred while enabling MiniMessageAnywhere v2.1.0 (Is it up to date?)
me.gepron1x.libraries.cloud.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: paper brigadier initialization failure (null)
        at me.gepron1x.libraries.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:133) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.minimessageanywhere.MiniMessageAnywhere.setupCommand(MiniMessageAnywhere.java:173) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.minimessageanywhere.MiniMessageAnywhere.enable(MiniMessageAnywhere.java:95) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.minimessageanywhere.MiniMessageAnywhere.onEnable(MiniMessageAnywhere.java:69) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1172) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1574]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at me.gepron1x.libraries.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:110) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.libraries.cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:80) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.libraries.cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:73) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.libraries.cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.libraries.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:127) ~[MiniMessageAnywhere-2.1.0.jar:?]
        ... 14 more
Caused by: java.lang.NoSuchFieldException
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at me.gepron1x.libraries.cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:107) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.libraries.cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:80) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.libraries.cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:73) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.libraries.cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[MiniMessageAnywhere-2.1.0.jar:?]
        at me.gepron1x.libraries.cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:127) ~[MiniMessageAnywhere-2.1.0.jar:?]
        ... 14 more
[06:48:46 INFO]: [MiniMessageAnywhere] Disabling MiniMessageAnywhere v2.1.0
[06:48:46 INFO]: [MiniMessageAnywhere] Plugin disabled, cya!

**Comment by gepron1x** [comment]
Исправлю в следующем релизе.

**Comment by kotazzz** [comment]
Когда релиз для 1.18.2? Плагин очень обнадеживающий и полезный, на самом деле

**Comment by gepron1x** [comment]
> Когда релиз для 1.18.2? Плагин очень обнадеживающий и полезный, на самом деле
> 
> P.S. Поддерживается ли (точнее, будет ли) Purpur?
Постараюсь релизнуть как можно скорее. Сейчас я чутка занят. В дискорде есть версия, работающая на 1.18.2.

**Comment by kotazzz** [comment]
> Постараюсь релизнуть как можно скорее. Сейчас я чутка занят. В дискорде есть версия, работающая на 1.18.2.
Где найти дискорд сервер?

**Comment by gepron1x** [comment]
> > Постараюсь релизнуть как можно скорее. Сейчас я чутка занят. В дискорде есть версия, работающая на 1.18.2.
> > Где найти дискорд сервер?


https://discord.gg/VsRz5T67sG

**Comment by gepron1x** [comment]
Исправлено в новом релизе.
