### ISSUE TITLE
Error Unhandled exception occurred in onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by Hypick122** [gepron1x/minimessage-anywhere#7]
Error appears after joining a player to the server.
version: git-Purpur-1894 (MC: 1.19.3)

[04:04:58 ERROR]: [MiniMessageAnywhere] Unhandled exception occurred in onPacketSending(PacketEvent) for MiniMessageAnywhere
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.wrappers.PlayerInfoData.getProfile()" because "pid" is null
        at me.gepron1x.minimessageanywhere.packetlistener.out.PlayerInfoListener.onPacketSending(PlayerInfoListener.java:27) ~[MiniMessageAnywhere-2.2.1.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib_612.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib_612.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib_612.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib_612.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib_612.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib_612.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib_612.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib_612.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib_612.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2234) ~[?:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:341) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:594) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1594) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1894]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[04:04:58 ERROR]: Parameters:
  net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket@78cd4b5b[
    a=[ADD_PLAYER, INITIALIZE_CHAT, UPDATE_GAME_MODE, UPDATE_LISTED, UPDATE_LATENCY, UPDATE_DISPLAY_NAME]
    b=[b[profileId=e65ba7e7-f463-3c5f-a917-d3def772d0b4, profile=com.mojang.authlib.GameProfile@3d439bad[id=e65ba7e7-f463-3c5f-a917-d3def772d0b4,name=Hypick122,properties={textures=[com.mojang.authlib.properties.Property@2f309a34]},legacy=false], listed=true, latency=0, gameMode=SURVIVAL, displayName=null, chatSession=null]]
  ]

**Comment by gepron1x** [comment]
Will be fixed in next minor release

**Comment by gepron1x** [comment]
Fixed in new release

**Comment by Hypick122** [comment]
The error did not disappear with the update. Logs:
[latest.log](https://github.com/gepron1x/minimessage-anywhere/files/10489177/latest.log)

**Comment by Hypick122** [comment]
> Исправлено в новой версии

Ошибка не исчезла с обновлением. Логи:
[latest.log](https://github.com/gepron1x/minimessage-anywhere/files/10493241/latest.4.log)

**Comment by gepron1x** [comment]
Да блять
