### ISSUE TITLE
Error with loading on 1.18.2 purpur

### ISSUE THREAD

**Issue by Szabolcs24** [gepron1x/minimessage-anywhere#9]
```
[11:27:39] [Server thread/INFO]: [MiniMessageAnywhere] Enabling MiniMessageAnywhere v2.2.2
[11:27:39] [Server thread/ERROR]: Error occurred while enabling MiniMessageAnywhere v2.2.2 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage$Builder net.kyori.adventure.text.minimessage.MiniMessage$Builder.preProcessor(java.util.function.UnaryOperator)'
	at me.gepron1x.minimessageanywhere.MiniMessageAnywhere.enable(MiniMessageAnywhere.java:92) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at me.gepron1x.minimessageanywhere.MiniMessageAnywhere.onEnable(MiniMessageAnywhere.java:71) ~[MiniMessageAnywhere-2.2.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:27:39] [Server thread/INFO]: [MiniMessageAnywhere] Disabling MiniMessageAnywhere v2.2.2
[11:27:39] [Server thread/INFO]: [MiniMessageAnywhere] Plugin disabled, cya!
```

**Comment by gepron1x** [comment]
Purpur contains an older version of MiniMessage. You can try using mma-legacy jar.
